# Generated by Django 2.2.3 on 2022-06-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
                ('language', models.CharField(choices=[('ENG', 'English'), ('HIN', 'Hindi')], max_length=3)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('INR', 'Indian Rupee')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='poly', max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('geojson', models.TextField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Provider')),
            ],
        ),
    ]
